In [6]:
import numpy as np
# Importing NumPy library for working with arrays and numerical operations
def create_array():  # Asking the user what type of array they want to create
    print("Select the type of array to create:")
    print("1. 1D Array\n2. 2D Array\n3. 3D Array")
    array_type = int(input("Enter your choice: "))  # Taking input from the user for the type of array

    if array_type == 1:  # If user selects 1D array
        elements = list(map(int, input("Enter elements for 1D array separated by space: ").split()))  # Taking input elements from user, converting them to a list of integers
        array = np.array(elements)  # Creating a 1D NumPy array
    elif array_type == 2:  # If user selects 2D array
        rows = int(input("Enter number of rows: ")) # asking row
        cols = int(input("Enter number of columns: ")) # asking colume
        elements = list(map(int, input(f"Enter {rows * cols} elements separated by space: ").split()))
         # Creating a 2D NumPy array with the given shape
        array = np.array(elements).reshape(rows, cols)
    elif array_type == 3:  # If user selects 3D array
        depth = int(input("Enter depth: "))
        rows = int(input("Enter number of rows: "))
        cols = int(input("Enter number of columns: "))
        elements = list(map(int, input(f"Enter {depth * rows * cols} elements separated by space: ").split()))
        # Creating a 3D NumPy array with the given shape
        array = np.array(elements).reshape(depth, rows, cols)
    else:
        print("Invalid choice!") # if choice invalid
        return None  # Returning None since no array is created

    print("Array created successfully:")
    print(array) # displaying the creating array

    while True: # Infinite loop to allow user operations on the array
        print("Choose an operation:") # user to select the option
        print("1. Indexing\n2. Slicing\n3. Go Back")
        operation_choice = int(input("Enter your choice: "))
         # If user chooses indexing
        if operation_choice == 1:
            print("Indexed Value:", array[0])
             # If user chooses slicing
        elif operation_choice == 2:
            row_range = input("Enter the row range (start:end): ") # Enter row and column
            col_range = input("Enter the column range (start:end): ")
            # Splitting and converting input values into integers
            row_start, row_end = map(int, row_range.split(':'))
            col_start, col_end = map(int, col_range.split(':'))
            # Displaying the sliced portion of the array
            print("Sliced Array:")
            print(array[row_start:row_end, col_start:col_end])
        elif operation_choice == 3: # If user chooses to exit the loop
            break # Exiting the loop
        else:
            print("Invalid choice, please try again!")  # Displaying an error message

    return array # Returning the final array after operations

def perform_math_operations(array): # Function to perform mathematical operations on the array
    if array is None: # Checking if the array is None (not created)
        print("No array found. Please create an array first.")
        return
    print("Choose a mathematical operation:") # Asking the user to select a mathematical operation
    print("1. Addition\n2. Subtraction\n3. Multiplication\n4. Division")
    choice = int(input("Enter your choice: "))
    # Asking the user to enter a second array with the same size
    elements = list(map(int, input(f"Enter {array.size} same-size array elements separated by space: ").split()))
    # Creating a second array with the same shape as the first one
    second_array = np.array(elements).reshape(array.shape)

    print("Original Array:") # Printing the original array
    print(array)
    print("Second Array:") # Printing the second array
    print(second_array)

    if choice == 1:
        result = array + second_array # Addition of two arrays
    elif choice == 2:
        result = array - second_array # Subtraction of two arrays
    elif choice == 3:
        result = array * second_array # Element-wise multiplication of two arrays
    elif choice == 4:
        result = array / second_array # Element-wise division of two arrays
    else:
        print("Invalid choice!")
        return  # Exiting the function

    print("Result of Operation:") # Printing the result of the mathematical operation
    print(result)

def combine_or_split_array(array): # Function to either combine or split an array
    if array is None: # Checking if array exists, otherwise asking the user to create one
        print("No array found. Please create an array first.")
        return  # Exit function
    print("Choose an option:")  # Asking the user whether they want to combine or split the array
    print("1. Combine Arrays\n2. Split Array")
    choice = int(input("Enter your choice: "))

    if choice == 1: # If the user chooses to combine arrays
        elements = list(map(int, input(f"Enter {array.shape[1]} elements for another array to combine separated by space: ").split()))
        # Creating a second array from user input with a shape of (1, -1) (one row, multiple columns)
        second_array = np.array(elements).reshape(1, -1)
        # Stacking the original and second array vertically
        combined_array = np.vstack((array, second_array))
        print("Original Array:") # original array
        print(array)
        print("Second Array:")
        print(second_array)
        print("Combined Array (Vertical Stack):") # Printing the combined array after vertical stacking
        print(combined_array)
    elif choice == 2:
        split_arrays = np.array_split(array, 2) # Splitting the array into 2 equal parts
        print("Split Arrays:")
        for part in split_arrays:
            print(part)
    else:
        print("Invalid choice!")

def search_sort_filter(array):
    if array is None:  # Check if array exists
        print("No array found. Please create an array first.")
        return # Exit the function
        # Asking user for search, sort, or filter operation
    print("Choose an option:\n1. Search a value\n2. Sort the array\n3. Filter values")
    choice = int(input("Enter your choice: "))

    if choice == 2:
        sorted_array = np.sort(array, axis=-1)  # Sorting the array along the last axis (-1 means sorting row-wise)
        print("Sorted Array:")
        print(sorted_array)

def compute_aggregates(array):
    if array is None: # Check if array exists
        print("No array found. Please create an array first.")
        return # Exit function
    print("Choose an aggregate/statistical operation:")
    print("1. Sum\n2. Mean\n3. Median\n4. Standard Deviation\n5. Variance")
    choice = int(input("Enter your choice: "))
    # Performing the selected operation

    if choice == 1:
        result = np.sum(array) # Sum of all elements
    elif choice == 2:
        result = np.mean(array)  # Mean (average)
    elif choice == 3:
        result = np.median(array) # Median (middle value)
    elif choice == 4:
        result = np.std(array) # Standard deviation
    elif choice == 5:
        result = np.var(array) # Variance
    else:
        print("Invalid choice!")
        return

    print(f"Result: {result}")

def main():
    print("Welcome to the NumPy Analyzer!")
    array = None  #Initialize array as None (No array is created initially)
    while True:  # Infinite loop to keep the program running until user exits
        print("Choose an option:")
        print("1. Create a Numpy Array\n2. Perform Mathematical Operations\n3. Combine or Split Arrays\n4. Search, Sort, or Filter Arrays\n5. Compute Aggregates and Statistics\n6. Exit")
        choice = int(input("Enter your choice: "))

        if choice == 1:
            array = create_array() # Function to create an array
        elif choice == 2:
            perform_math_operations(array) # Perform mathematical operations on array
        elif choice == 3:
            combine_or_split_array(array) # Combine or split an array
        elif choice == 4:
            search_sort_filter(array) # Search, sort, or filter array
        elif choice == 5:
            compute_aggregates(array) # Compute sum, mean, median, etc.
        elif choice == 6:
            print("Thank you for using the NumPy Analyzer! Goodbye!")
            break # Exit the loop
        else:
            print("Invalid choice, please try again!") # Handling wrong input

if __name__ == "__main__": # execute main function
    main()


Welcome to the NumPy Analyzer!
Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit
Enter your choice: 1
Select the type of array to create:
1. 1D Array
2. 2D Array
3. 3D Array
Enter your choice: 2
Enter number of rows: 2
Enter number of columns: 3
Enter 6 elements separated by space: 10 20 30 40 50 60
Array created successfully:
[[10 20 30]
 [40 50 60]]
Choose an operation:
1. Indexing
2. Slicing
3. Go Back
Enter your choice: 2
Enter the row range (start:end): 0:2
Enter the column range (start:end): 1:3
Sliced Array:
[[20 30]
 [50 60]]
Choose an operation:
1. Indexing
2. Slicing
3. Go Back
Enter your choice: 3
Choose an option:
1. Create a Numpy Array
2. Perform Mathematical Operations
3. Combine or Split Arrays
4. Search, Sort, or Filter Arrays
5. Compute Aggregates and Statistics
6. Exit
Enter your choice: 3
Choose an option:
1. Combine Arrays
2. Split Ar